# Create a dockerfile with node image
FROM node:14

WORKDIR /workspaces/CopilotHackathon/exercisefiles/node

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 4000

CMD ["node", "nodeserver.js"]

# Create a directory to hold the application code inside the image, this will be the working directory for your application

# Set the working directory to /usr/src/app

# Copy package.json and package-lock.json to the working directory

# Install npm 

# Copy the current directory contents into the container at /usr/src/app

# Make port 3000 available to the world outside this container

# Run Nodeserver.js when the container launches

# Write a docker command to build the image and tag it as mynodeapp
# docker build -t mynodeapp .
